Add some hacky debug

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -3,6 +3,13 @@
 set -e
 
 mkdir -p "$1/bin/"
+if [[ ! -f bin/nginx ]]; then
+    echo "-----> nginx-buildpack: fatal error, missing bin/nginx"
+    echo "BUILD_DIR = $1"
+    pwd
+    find .
+    exit 1
+fi
 cp bin/nginx "$1/bin/"
 nginx_version=$(./bin/nginx -V 2>&1 | head -1 | awk '{ print $NF }')
 echo "-----> nginx-buildpack: Installed ${nginx_version} to app/bin"
